---
- name: basic - common programs
  apt:
    pkg:
      # basic ######################################
      - python-pip
      - python3-pip
      - tree
      - trash-cli
      - xclip
      - curl
      - terminator
      - smbclient

      # infra ######################################
      - htop
      - ncdu

      # dev ########################################
      # version control
      - git
      - subversion
      - mercurial

      # databases
      - mysql-server
      - mysql-client
      - libmysqlclient-dev # to be able to pip install MySQL-python
      - postgresql

      # dev tools
      - nodejs
      - ruby-sass
      - silversearcher-ag
  become: true

- name: basic - enumerate home subdirs for links
  find: path="{{ files_home }}" hidden=yes recurse=yes file_type=directory
  register: home_subdirs

- name: basic - create home subdirs
  file:
    src: "{{ item.path }}"
    dest: "{{ home }}/{{ item.path | relpath(files_home) }}"
    state: directory
    force: yes
  with_items: "{{ home_subdirs.files }}"

- name: basic - enumerate files to link at home
  find: path="{{ files_home }}" hidden=yes recurse=yes file_type="{{ item }}"
  register: home_files
  loop:
    - file
    - link

- name: basic - link files at home
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | relpath(files_home) }}"
    state: link
    force: yes
  loop: "{{ home_files.results | map(attribute='files') | flatten | map(attribute='path') | list }}"


- name: Remove unnecessary hunspell dicts
  # important to reduce languages in firefox spell checking
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - '/usr/share/hunspell/en_*'
  when: item is not search("en_US")
  become: true
