---
- name: basic - common programs
  apt:
    pkg: "{{ item }}"
  become: true
  with_items:

    # basic ######################################
    - python-pip
    - python3-pip
    - tree
    - trash-cli
    - xclip
    - curl
    - terminator

    # infra ######################################
    - htop

    # dev ########################################
    # version control
    - git
    - gitk
    - subversion
    - mercurial

    # databases
    - mysql-server
    - mysql-client
    - libmysqlclient-dev # to be able to pip install MySQL-python
    - postgresql

    # dev tools
    - ruby-sass
    - silversearcher-ag

- name: basic - enumerate .config files
  find: path="{{ confdir }}/files/config"
  register: config_files

- name: basic - link .config files
  file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.config/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ config_files.files }}"

- name: basic - general configuration files at home
  file:
    src: "{{ files }}/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .agignore

