---
- name: basic - common programs
  apt:
    pkg: "{{ item }}"
  become: true
  with_items:

    # basic ######################################
    - python-pip
    - python3-pip
    - tree
    - trash-cli
    - xclip
    - curl
    - terminator

    # dev ########################################
    # version control
    - git
    - gitk
    - subversion
    - mercurial

    # databases
    - mysql-server
    - mysql-client
    - libmysqlclient-dev # to be able to pip install MySQL-python
    - mysql-workbench
    - postgresql
    - pgadmin3

    # dev tools
    - ruby-sass
    - silversearcher-ag

    # desktop apps ###############################
    - vlc
    - gimp
    - imagemagick
    - chromium-browser
    - unity-tweak-tool
    - gnome-tweak-tool
    - anki
    - audacity
    - mplayer
    - redshift

    # p/ o banco do brasil ########################
    - openjdk-8-jre
    - icedtea-8-plugin

- name: basic - enumerate .config files
  find: path="{{ confdir }}/files/config"
  register: config_files

- name: basic - link .config files
  file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.config/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: config_files.files



