---
- name: common programs
  apt:
    pkg: "{{ item }}"
  become: true
  with_items:

    # basic ######################################
    - python-pip
    - python3-pip
    - tree
    - trash-cli
    - xclip
    - curl
    - terminator

    # dev ########################################
    # version control
    - git
    - gitk
    - subversion
    - mercurial

    # databases
    - mysql-server
    - mysql-client
    - libmysqlclient-dev # to be able to pip install MySQL-python
    - mysql-workbench
    - postgresql
    - pgadmin3

    # dev tools
    - ruby-sass
    - silversearcher-ag

    # desktop apps ###############################
    - vlc
    - gimp
    - imagemagick
    - chromium-browser
    - unity-tweak-tool
    - gnome-tweak-tool
    - anki
    - audacity
    - mplayer
    - redshift

- file:
    src: "{{ confdir }}/files/redshift.conf"
    dest: "{{ home }}/.config/redshift.conf"
    state: link
    force: yes
