---
- name: desktop -- dconf customizations
  command: dconf write {{ item }}
  with_items:
  # disable show hud on Alt
  - /org/compiz/integrated/show-hud '[""]'
  # workspaces 2x2
  - /org/compiz/profiles/unity/plugins/core/hsize 2
  - /org/compiz/profiles/unity/plugins/core/vsize 2
  # turn Caps into another Ctrl
  - /org/gnome/desktop/input-sources/xkb-options "['ctrl:nocaps']"
  # auto hide launcher
  - /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode 1
  # transparent upper panel
  - /org/compiz/profiles/unity/plugins/unityshell/panel-opacity 0.0
  # disable Integration Prompts
  - /com/canonical/unity/webapps/preauthorized-domains "@as []"
  - /com/canonical/unity/webapps/integration-allowed "false"
  # disable Search online sources
  - /com/canonical/unity/lenses/remote-content-search "'none'"
  # show date on clock widget
  - /com/canonical/indicator/datetime/show-date "true"

  # TODO... general desktop scaling (set manually in Display > Scale for menu and title bars)

  # revert to this as soon as the package is available in wily:
  # - apt_repository: repo='ppa:indicator-brightness/ppa'
- name: desktop -- add brightness indicator apt repo
  apt_repository: repo="{{ item }}"
  with_items:
  - deb http://ppa.launchpad.net/indicator-brightness/ppa/ubuntu vivid main
  - deb-src http://ppa.launchpad.net/indicator-brightness/ppa/ubuntu vivid main
  become: true

- name: desktop -- brightness indicator
  apt: name=indicator-brightness
  become: true
