---
- name: desktop - common programs
  apt:
    pkg:
      # general desktop apps
      - vlc
      - gimp
      - imagemagick
      - unity-tweak-tool
      - gnome-tweak-tool
      - audacity
      - mplayer
      - gnome-shell-pomodoro

      # for banco do brasil
      - openjdk-8-jre
      - icedtea-8-plugin

      # database visual clients
      - mysql-workbench
      - pgadmin3
  become: true


- name: desktop - turn off wi-fi when on wired network connection
  file:
    src: "{{ files }}/99-wlan"
    dest: "/etc/NetworkManager/dispatcher.d/99-wlan"
    state: link
    force: yes
    owner: root
  become: true


- name: desktop -- dconf customizations
  command: dconf write {{ item }}
  with_items:
  # disable show hud on Alt
  - /org/compiz/integrated/show-hud '[""]'
  # workspaces 2x2
  # TODO ... install here (now it's still manual)
  # ---->>>> https://extensions.gnome.org/extension/484/workspace-grid/
  - /org/gnome/desktop/wm/preferences/num-workspaces 4
  - /org/gnome/shell/extensions/workspace-grid/num-columns 2
  - /org/gnome/shell/extensions/workspace-grid/show-workspace-labels "false"
  # Caps => another Ctrl, 2 shifts => caps on, one shift => caps off, right alt is compose (mainly to write ß)
  - /org/gnome/desktop/input-sources/xkb-options "['caps:ctrl_modifier', 'shift:both_capslock_cancel', 'compose:ralt']"
  # auto hide launcher
  - /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode 1
  # transparent upper panel
  - /org/compiz/profiles/unity/plugins/unityshell/panel-opacity 0.0
  # disable Integration Prompts
  - /com/canonical/unity/webapps/preauthorized-domains "@as []"
  - /com/canonical/unity/webapps/integration-allowed "false"
  # disable Search online sources
  - /com/canonical/unity/lenses/remote-content-search "'none'"
  # show date on clock widget
  - /com/canonical/indicator/datetime/show-date "true"
  # laucher favorites
  - /com/canonical/unity/launcher/favorites "['application://firefox.desktop', 'application://org.gnome.Nautilus.desktop', 'application://google-chrome.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"
  # use list view by default in nautilus
  - /org/gnome/nautilus/preferences/default-folder-viewer "'list-view'"
  # auto hide the dock
  - /org/gnome/shell/extensions/dash-to-dock/dock-fixed "false"
  # sounds and dark theme for gnome-shell-pomodoro
  - /org/gnome/pomodoro/preferences/enabled-plugins "['sounds', 'dark-theme']"
  # automatic timezone detection
  - /org/gnome/desktop/datetime/automatic-timezone "true"

