# from https://docs.docker.com/install/linux/docker-ce/ubuntu/
- apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  become: true

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: true

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: true

- apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true
