- apt: name=etckeeper
  become: true

- lineinfile: dest=/etc/etckeeper/etckeeper.conf regexp='^VCS=' line='VCS="git"'
  become: true

- shell: etckeeper init && etckeeper commit "Init"
  become: true
  args:
    creates: /etc/.git
