---
- name: devtools - common programs
  apt:
    pkg:
      # databases
      - mysql-server
      - mysql-client
      - libmysqlclient-dev # to be able to pip install MySQL-python
      - postgresql

      # dev tools
      - nodejs
      - ruby-sass

- name: devtools -- geckodriver
  unarchive:
    src: 'https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz'
    dest: /usr/bin
    remote_src: yes
  become: yes
