- name: node -- check if node is absent
  shell: node --version
  register: check_node_present
  ignore_errors: True

- name: node -- pre install
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  when: check_node_present is failed

- name: node -- install
  apt: name=nodejs
  become: true
  when: check_node_present is failed

- name: node - custom packages
  npm: name="{{ item }}" global=yes
  with_items:
  - less
  - grunt
  - grunt-cli
  become: true

