---
- apt_repository: repo='ppa:numix/ppa'
  become: true

- apt:
    name:
      - numix-gtk-theme
      - numix-icon-theme-circle
  become: true

- command: dconf write /org/gnome/desktop/interface/gtk-theme "'Numix'"
- command: dconf write /org/gnome/desktop/interface/icon-theme "'Numix-Circle'"
