- pip:
    name:
      - docutils
      - virtualenvwrapper
    state: latest
  become: true

- pip:
    name:
      - docutils
      - ipython
    state: latest
    executable: pip3
  become: true


# TODO temporary ... REMOVE when python 3.8 is part of os distribution
- name: python - temp enable python 3.8
  apt_repository: repo='ppa:deadsnakes/ppa'
  become: true

- apt:
    name:
      # to enable copy and paste in IPython
      - python-tk
      - python3-tk

      # for Plone 4
      # http://plone.org/documentation/manual/installing-plone/installing-on-linux-unix-bsd/debian-libraries
      - build-essential
      - libbz2-dev
      - libjpeg62-dev
      - libreadline-gplv2-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - poppler-utils
      - python-dev
      - wv
      - zlib1g-dev
      - xpdf # XXX isso é para o portal modelo???

      # for psycopg
      - libpq-dev

      # more
      - graphviz
      - graphviz-dev

      # TODO temporary ... REMOVE when python 3.8 is part of os distribution
      - python3.8
      - python3.8-dev

  become: true


# previously used
#    apt: name=python-ldap state=build-dep
#  but that stopped working on 16.04 (xenial)
#  I think that's no longer necessary... but should keep an eye on it
- apt: name=python-ldap
  become: true

# IPython startup scripts
- command: ipython profile create
- command: ipython profile create zope2
- file:
    src: "{{ files }}/ipython/{{ item | basename }}"
    dest: "{{ home }}/.ipython/{{ item }}"
    state: link
    force: yes
  with_items:
    - profile_default/ipython_config.py
    - profile_default/startup/virtualenv-for-ipython.py
    - profile_default/startup/autowidth.py

    - profile_zope2/ipython_config.py
    - profile_zope2/startup/ipy_profile_zope.py
    - profile_zope2/startup/autowidth.py

# buildout
- file: state=directory path="{{ home }}/.buildout"
- file: state=directory path="{{ home }}/.buildout/eggs"
- file: state=directory path="{{ home }}/.buildout/downloads"
- file: state=directory path="{{ home }}/.buildout/extends"
- template: src=buildout/default.cfg dest="{{ home }}/.buildout/default.cfg"

# virtualenvwrapper automatic actions
- file:
    src: "{{ files }}/virtualenvs/{{ item }}"
    dest: "{{ home }}/.virtualenvs/{{ item }}"
    state: link
    force: yes
  with_items:
    - postactivate
    - postdeactivate
    - postmkvirtualenv
