---
- name: spotify - install snap first
  apt:
    pkg: snap
  become: true

- name: spotify -- install
  command: snap install spotify
  become: true

- file:
    src: "{{ files }}/spotify_spotify.desktop"
    dest: "/var/lib/snapd/desktop/applications/spotify_spotify.desktop"
    state: link
    owner: root
    force: yes
  become: true
