---
# vim with python 3 support
# based on http://www.xorpd.net/blog/vim_python3_install.html

- name: vim -- check if vim is absent
  shell: vim --version | grep -q '+python3'
  register: check_vim_absent
  ignore_errors: True

- name: vim -- deps
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - python3-dev
    - ruby
    - ruby-dev
    - libx11-dev
    - libxt-dev
    - libgtk2.0-dev
    - libncurses5
    - ncurses-dev
    - exuberant-ctags
  become: true
  when: check_vim_absent.rc

- name: vim -- clone repo
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim
  when: check_vim_absent.rc

- name: vim -- grab python3 config dir
  shell: python3-config --configdir
  register: python3_config_dir
  when: check_vim_absent.rc

- name: vim -- configure
  shell: "./configure
          --enable-perlinterp
          --enable-python3interp
          --enable-rubyinterp
          --enable-cscope
          --enable-gui=auto
          --enable-gtk2-check
          --enable-gnome-check
          --with-features=huge
          --enable-multibyte
          --with-x
          --with-python3-config-dir={{  python3_config_dir.stdout }}"
  args:
    chdir: /tmp/vim
  when: check_vim_absent.rc

- name: vim -- make
  shell: make
  args:
    chdir: /tmp/vim
  when: check_vim_absent.rc

- name: vim -- make install
  shell: make install
  args:
    chdir: /tmp/vim
  become: true
  when: check_vim_absent.rc

######## my personal vim configs ########

- name: vim -- clone my personal vim configs
  git:
    repo: git@github.com:marciomazza/vimrc.git
    dest: "{{ confdir }}/vimrc"

- name: vim -- link .vimrc
  file:
    src: "{{ confdir }}/vimrc/.vimrc"
    dest: "{{ home }}/.vimrc"
    state: link

- name: vim -- install requirements
  pip:
    requirements: "{{ confdir }}/vimrc/requirements.txt"
  become: true

# setup powerline fonts

- name: vim -- powerline -- check absent
  shell: ls /usr/share/fonts/PowerlineSymbols.otf && ls /etc/fonts/conf.d/10-powerline-symbols.conf
  register: check_powerline_absent
  ignore_errors: True

- name: vim -- powerline -- download PowerlineSymbols.otf
  get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: /usr/share/fonts/
  become: true
  when: check_powerline_absent.rc

- name: vim -- powerline -- update font cache
  shell: sudo fc-cache -vf
  become: true
  when: check_powerline_absent.rc

- name: vim -- powerline -- download 10-powerline-symbols.conf
  get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
    dest: /etc/fonts/conf.d/
  become: true
  when: check_powerline_absent.rc

# install Plug and all plugins

- name: vim - create autoload dir
  file: path="{{ home }}/.vim/autoload" state=directory

- name: vim - Download Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.vim/autoload/plug.vim"

- name: vim - Install all plugins
  command: vim +PlugInstall +qall
