---
# based on http://www.xorpd.net/blog/vim_python3_install.html
# and https://github.com/ycm-core/YouCompleteMe/wiki/Building-Vim-from-source

- name: vim -- check if vim2 is absent
  shell: vim --version
  register: check_vim_absent
  ignore_errors: True

- name: vim -- deps
  apt:
    pkg:
      - vim-gnome
      - python-dev
      - libx11-dev
      - libxt-dev
      - libgtk2.0-dev
      - libncurses5
      - ncurses-dev
      - exuberant-ctags
  become: true

- name: vim -- clone repo (for python 2 vim)
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ home }}/repos/vim"
  when: check_vim_absent.rc

- name: vim -- grab python 2 config dir
  shell: python3.8-config --configdir
  register: python_config_dir
  when: check_vim_absent.rc

- name: vim -- configure (for python 2 vim)
  shell: "./configure
          --with-features=huge
          --enable-python3interp
          --enable-cscope
          --enable-gui=auto
          --enable-gtk2-check
          --enable-gnome-check
          --enable-multibyte
          --with-x
          --with-python3-config-dir={{ python_config_dir.stdout }}"
  args:
    chdir: /tmp/vim
  when: check_vim_absent.rc

- name: vim -- make
  shell: make
  args:
    chdir: /tmp/vim
  when: check_vim_absent.rc

- name: vim -- make install
  shell: make install
  args:
    chdir: /tmp/vim
  become: true
  when: check_vim_absent.rc

# TODO ...
# test that this is working
#
# automate...
#
# sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 1
# sudo update-alternatives --set editor /usr/local/bin/vim
# sudo update-alternatives --install /usr/bin/vi vi /usr/local/bin/vim 1
# sudo update-alternatives --set vi /usr/local/bin/vim


######## my personal vim configs ########

- name: vim -- directory for personal config
  file:
    path: "{{ confdir }}/vimrc"
    state: directory

- name: vim -- clone my personal vim config
  git:
    repo: git@github.com:marciomazza/vimrc.git
    dest: "{{ confdir }}/vimrc"

- name: vim -- link .vimrc
  file:
    src: "{{ confdir }}/vimrc/.vimrc"
    dest: "{{ home }}/.vimrc"
    state: link

- name: vim -- install requirements for python 3
  pip:
    executable: pip3
    requirements: "{{ confdir }}/vimrc/requirements.txt"
  become: true

# setup powerline fonts

- name: vim -- powerline -- check absent
  shell: ls /usr/share/fonts/PowerlineSymbols.otf && ls /etc/fonts/conf.d/10-powerline-symbols.conf
  register: check_powerline_absent
  ignore_errors: True

- name: vim -- powerline -- download PowerlineSymbols.otf
  get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: /usr/share/fonts/
  become: true
  when: check_powerline_absent.rc

- name: vim -- powerline -- update font cache
  shell: sudo fc-cache -vf
  become: true
  when: check_powerline_absent.rc

- name: vim -- powerline -- download 10-powerline-symbols.conf
  get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
    dest: /etc/fonts/conf.d/
  become: true
  when: check_powerline_absent.rc

# install Plug and all plugins

- name: vim - create autoload dir
  file: path="{{ home }}/.vim/autoload" state=directory

- name: vim - Download Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.vim/autoload/plug.vim"

- name: vim - Install all plugins
  shell: vim -c ":PlugInstall" -c qa
  no_log: true
