---
- name: common programs
  apt:
    pkg: "{{ item }}"
  sudo: yes
  with_items:

    # basic
    - tree
    - trash-cli
    - xclip
    - curl
    - terminator

    # dev
    - subversion
    - mercurial
    - mysql-server
    - mysql-client
    - libmysqlclient-dev # to be able to pip install MySQL-python
    - mysql-workbench
    - postgresql
    - pgadmin3

    # apps
    - vlc
    - gimp
    - imagemagick
    - chromium-browser
    - unity-tweak-tool
    - gnome-tweak-tool
