---
- name: git - deps
  apt:
    pkg: "{{ item }}"
  with_items:
    - git
    - gitk
    - git-svn
    - meld
  sudo: yes

- name: git - link .gitignore
  file:
    src: "{{ ansible_env.HOME }}/.z/roles/common/files/.gitignore"
    dest: "{{ ansible_env.HOME }}/.gitignore"
    state: link

- name: git - global configs
  command: git config --global {{ item }}
  with_items:
  - color.ui true
  - diff.tool meld
  - merge.tool meld
  - core.excludesfile ~/.gitignore
  - alias.st status
  - alias.ci commit
  - alias.co checkout
  - alias.df 'diff --color-words'
  - user.name '{{ fullname }}'
  - user.email '{{ email }}'
  # explicitly adopt default push behaviour of git 2.0 and stop warning message
  - push.default simple

