---
# vim with python 3 support
# based on http://www.xorpd.net/blog/vim_python3_install.html

- apt:
    pkg: "{{ item }}"
  with_items:
    - python-dev
    - python3-dev
    - ruby
    - ruby-dev
    - libx11-dev
    - libxt-dev
    - libgtk2.0-dev
    - libncurses5
    - ncurses-dev
  sudo: yes

- git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim

- shell: python3-config --configdir
  register: python3_config_dir

- shell: "./configure
          --enable-perlinterp
          --enable-python3interp
          --enable-rubyinterp
          --enable-cscope
          --enable-gui=auto
          --enable-gtk2-check
          --enable-gnome-check
          --with-features=huge
          --enable-multibyte
          --with-x
          --with-python3-config-dir={{  python3_config_dir.stdout }}"
  args:
    chdir: /tmp/vim

- shell: make
  args:
    chdir: /tmp/vim

- shell: make install
  args:
    chdir: /tmp/vim
  sudo: yes

# my personal vim configs

- git:
    repo: git@github.com:marciomazza/vimrc.git
    dest: "{{ confdir }}/vimrc"

- file:
    src: "{{ confdir }}/vimrc/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link

- pip:
    requirements: "{{ confdir }}/vimrc/requirements.txt"
  sudo: yes

# setup powerline fonts

- get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: /usr/share/fonts/
  sudo: yes

- shell: sudo fc-cache -vf
  sudo: yes

- get_url:
    url: https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
    dest: /etc/fonts/conf.d/
  sudo: yes


